const ActionTypes = {
  FOCUS_WINDOW: 'FOCUS_WINDOW',
  REQUEST_MANIFEST: 'REQUEST_MANIFEST',
  RECEIVE_MANIFEST: 'RECEIVE_MANIFEST',
  ADD_MANIFEST: 'ADD_MANIFEST',
  ADD_WINDOW: 'ADD_WINDOW',
  NEXT_CANVAS: 'NEXT_CANVAS',
  PREVIOUS_CANVAS: 'PREVIOUS_CANVAS',
  REMOVE_WINDOW: 'REMOVE_WINDOW',
  PICK_WINDOWING_SYSTEM: 'PICK_WINDOWING_SYSTEM',
  REQUEST_MANIFEST: 'REQUEST_MANIFEST',
  RECEIVE_MANIFEST: 'RECEIVE_MANIFEST'
};

export default ActionTypes;
