const ActionTypes = {
  FOCUS_WINDOW: 'FOCUS_WINDOW',
  ADD_MANIFEST: 'ADD_MANIFEST',
  ADD_WINDOW: 'ADD_WINDOW',
  NEXT_CANVAS: 'NEXT_CANVAS',
  PREVIOUS_CANVAS: 'PREVIOUS_CANVAS',
  SET_CANVAS: 'SET_CANVAS',
  UPDATE_WINDOW_POSITION: 'UPDATE_WINDOW_POSITION',
  REMOVE_WINDOW: 'REMOVE_WINDOW',
  PICK_WINDOWING_SYSTEM: 'PICK_WINDOWING_SYSTEM',
  REQUEST_MANIFEST: 'REQUEST_MANIFEST',
  RECEIVE_MANIFEST: 'RECEIVE_MANIFEST',
  RECEIVE_MANIFEST_FAILURE: 'RECEIVE_MANIFEST_FAILURE',
  SET_CONFIG: 'SET_CONFIG',
  UPDATE_CONFIG: 'UPDATE_CONFIG',
  REMOVE_MANIFEST: 'REMOVE_MANIFEST',
  REQUEST_INFO_RESPONSE: 'REQUEST_INFO_RESPONSE',
  RECEIVE_INFO_RESPONSE: 'RECEIVE_INFO_RESPONSE',
  RECEIVE_INFO_RESPONSE_FAILURE: 'RECEIVE_INFO_RESPONSE_FAILURE',
  REMOVE_INFO_RESPONSE: 'REMOVE_INFO_RESPONSE',
};

export default ActionTypes;
